import type { Metadata } from "next";
import "@/styles/style.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger className="absolute top-1 left-1" />
          <main className="container w-full px-10 pt-10 pb-6">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
